var pins_config = {
	'default':{
		'pinShadow':'#000', //shadow color below the points
		'pinShadowOpacity':'50', //shadow opacity, value, 0-100"
	},
	'points':[
	//  {
	// 	'shape':'rectangle',//choose the shape of the pin circle or rectangle
	  	// 'hover':'<b><u>WASHINGTON DC</u></b><br><span style="color: yellow;">*Write text or load images*</span>',//the content of the hover ppup
	//  	'pos_X':587,//location of the pin on X axis
	// 	'pos_Y':182,//location of the pin on Y axis
	//  	'width':14,//width of the pin if rectangle (if circle use diameter)
 // 		'height':14,//height of the pin if rectangle (if circle delete this line)
	// 	'outline':'#FFF',//outline color of the pin
	// 	'thickness':1,//thickness of the line (0 to hide the line)
	//  	'upColor':'#0000FF',//color of the pin when map loads
	// 	'overColor':'#3399ff',//color of the pin when mouse hover
	// 	'downColor':'#00ffff',//color of the pin when clicked
	// 	//(trick, if you make this pin un-clickable > make the overColor and downColor the same)
	//  	'url':'#',//URL of this pin
	//  	'target':'new_window',//'new_window' opens URL in new window//'same_window' opens URL in the same window //'none' pin is not clickable
	//  	'enable':true,//true/false to enable/disable this pin
	//  },

// UTAH
	{
		'shape':'circle',
		'hover':'<b><u>Moab</u></b><br><span style="color: yellow;"><img src="/images/jeepontrail.jpg" alt="Jeep"></span>',
		'pos_X':180,
		'pos_Y':217,
		'diameter':10,
		'outline':'#FFF',
		'thickness':1,
		'upColor':'#FF0000',
		'overColor':'#FFEE88',
		'downColor':'#00ffff',
		'url':'#',
		'target':'same_window',
		'enable':true,
	},

// MONTANA
{
	'shape':'circle',
	'hover':'Butte',
	'pos_X':168.1,
	'pos_Y':92.25,
	'diameter':8,
	'outline':'#FFF',
	'thickness':1,
	'upColor':'#FF0000',
	'overColor':'#FFEE88',
	'downColor':'#00ffff',
	'url':'#',
	'target':'same_window',
	'enable':true,
},

	// {
	// 	'shape':'circle',
	// 	'hover':'New York',
	// 	'pos_X':616,
	// 	'pos_Y':140,
	// 	'diameter':14,
	// 	'outline':'#FFF',
	// 	'thickness':1,
	// 	'upColor':'#FF0000',
	// 	'overColor':'#FFEE88',
	// 	'downColor':'#00ffff',
	// 	'url':'#',
	// 	'target':'same_window',
	// 	'enable':true,
	// },
	// {
	// 	'shape':'circle',
	// 	'hover':'<b>Los Angeles</b><br><span style="color: yellow;">*Write text or load images*</span><br><span style="color: yellow;">*Link each pin to any webpage*</span>',
	// 	'pos_X':71,
	// 	'pos_Y':266,
	// 	'diameter':18,
	// 	'outline':'#FFF',
	// 	'thickness':1,
	// 	'upColor':'#FF0000',
	// 	'overColor':'#FFEE88',
	// 	'downColor':'#00ffff',
	// 	'url':'#',
	// 	'target':'same_window',
	// 	'enable':true,
	// },
	// {
	// 	'shape':'circle',
	// 	'hover':'Chicago',
	// 	'pos_X':448,
	// 	'pos_Y':156,
	// 	'diameter':14,
	// 	'outline':'#FFF',
	// 	'thickness':1,
	// 	'upColor':'#FF0000',
	// 	'overColor':'#FFEE88',
	// 	'downColor':'#00ffff',
	// 	'url':'#',
	// 	'target':'same_window',
	// 	'enable':true,
	// },
	// {
	// 	'shape':'circle',
	// 	'hover':'Houston',
	// 	'pos_X':369,
	// 	'pos_Y':353,
	// 	'diameter':14,
	// 	'outline':'#FFF',
	// 	'thickness':1,
	// 	'upColor':'#FF0000',
	// 	'overColor':'#FFEE88',
	// 	'downColor':'#00ffff',
	// 	'url':'#',
	// 	'target':'same_window',
	// 	'enable':true,
	// },
	// {
	// 	'shape':'circle',
	// 	'hover':'Phoenix',
	// 	'pos_X':142,
	// 	'pos_Y':284,
	// 	'diameter':14,
	// 	'outline':'#FFF',
	// 	'thickness':1,
	// 	'upColor':'#FF0000',
	// 	'overColor':'#FFEE88',
	// 	'downColor':'#00ffff',
	// 	'url':'#',
	// 	'target':'same_window',
	// 	'enable':true,
	// },
	// {
	// 	'shape':'circle',
	// 	'hover':'Seattle',
	// 	'pos_X':67,
	// 	'pos_Y':46,
	// 	'diameter':14,
	// 	'outline':'#FFF',
	// 	'thickness':1,
	// 	'upColor':'#FF0000',
	// 	'overColor':'#FFEE88',
	// 	'downColor':'#00ffff',
	// 	'url':'#',
	// 	'target':'same_window',
	// 	'enable':true,
	// },
	// {
	// 	'shape':'circle',
	// 	'hover':'Philadelphia',
	// 	'pos_X':605,
	// 	'pos_Y':159,
	// 	'diameter':14,
	// 	'outline':'#FFF',
	// 	'thickness':1,
	// 	'upColor':'#FF0000',
	// 	'overColor':'#FFEE88',
	// 	'downColor':'#00ffff',
	// 	'url':'#',
	// 	'target':'same_window',
	// 	'enable':true,
	// },
	// {
	// 	'shape':'circle',
	// 	'hover':'San Antonio',
	// 	'pos_X':320,
	// 	'pos_Y':362,
	// 	'diameter':14,
	// 	'outline':'#FFF',
	// 	'thickness':1,
	// 	'upColor':'#FF0000',
	// 	'overColor':'#FFEE88',
	// 	'downColor':'#00ffff',
	// 	'url':'#',
	// 	'target':'same_window',
	// 	'enable':true,
	// },
	// {
	// 	'shape':'circle',
	// 	'hover':'<b><u>Dallas</u></b><br><span style="color: #bcbcbc;">Street Address:</span><br>&nbsp;321 Example Road 9. County, State 54321<br><span style="color: #bcbcbc;">Telephone:</span><br>&nbsp;(256) 555-4321 / (256) 555-1234',
	// 	'pos_X':354,
	// 	'pos_Y':314,
	// 	'diameter':18,
	// 	'outline':'#FFF',
	// 	'thickness':1,
	// 	'upColor':'#FF0000',
	// 	'overColor':'#FFEE88',
	// 	'downColor':'#00ffff',
	// 	'url':'#',
	// 	'target':'same_window',
	// 	'enable':true,
	// },
	// {
	// 	'shape':'circle',
	// 	'hover':'Indianapolis',
	// 	'pos_X':474,
	// 	'pos_Y':184,
	// 	'diameter':14,
	// 	'outline':'#FFF',
	// 	'thickness':1,
	// 	'upColor':'#FF0000',
	// 	'overColor':'#FFEE88',
	// 	'downColor':'#00ffff',
	// 	'url':'#',
	// 	'target':'same_window',
	// 	'enable':true,
	// },
	// {
	// 	'shape':'circle',
	// 	'hover':'Jacksonville',
	// 	'pos_X':554,
	// 	'pos_Y':328,
	// 	'diameter':14,
	// 	'outline':'#FFF',
	// 	'thickness':1,
	// 	'upColor':'#FF0000',
	// 	'overColor':'#FFEE88',
	// 	'downColor':'#00ffff',
	// 	'url':'#',
	// 	'target':'same_window',
	// 	'enable':true,
	// },
	// {
	// 	'shape':'circle',
	// 	'hover':'San Francisco',
	// 	'pos_X':30,
	// 	'pos_Y':190,
	// 	'diameter':14,
	// 	'outline':'#FFF',
	// 	'thickness':1,
	// 	'upColor':'#FF0000',
	// 	'overColor':'#FFEE88',
	// 	'downColor':'#00ffff',
	// 	'url':'#',
	// 	'target':'same_window',
	// 	'enable':true,
	// },
	// {
	// 	'shape':'circle',
	// 	'hover':'Charlotte',
	// 	'pos_X':552,
	// 	'pos_Y':250,
	// 	'diameter':14,
	// 	'outline':'#FFF',
	// 	'thickness':1,
	// 	'upColor':'#FF0000',
	// 	'overColor':'#FFEE88',
	// 	'downColor':'#00ffff',
	// 	'url':'#',
	// 	'target':'same_window',
	// 	'enable':true,
	// },
	// {
	// 	'shape':'circle',
	// 	'hover':'Detroit',
	// 	'pos_X':501,
	// 	'pos_Y':145,
	// 	'diameter':14,
	// 	'outline':'#FFF',
	// 	'thickness':1,
	// 	'upColor':'#FF0000',
	// 	'overColor':'#FFEE88',
	// 	'downColor':'#00ffff',
	// 	'url':'#',
	// 	'target':'same_window',
	// 	'enable':true,
	// },
	// {
	// 	'shape':'circle',
	// 	'hover':'Juneau',
	// 	'pos_X':150,
	// 	'pos_Y':381,
	// 	'diameter':14,
	// 	'outline':'#FFF',
	// 	'thickness':1,
	// 	'upColor':'#FF0000',
	// 	'overColor':'#FFEE88',
	// 	'downColor':'#00ffff',
	// 	'url':'#',
	// 	'target':'same_window',
	// 	'enable':true,
	// },
	]
}
